POST http://127.0.0.1:5000/api/structures
Content-Type: application/json
{
    "directory": "/Users/collindutter/Documents/griptape/griptape-playground/src/misc/local-emulator/",
    "entry_file": "structure.py"
}

GET http://127.0.0.1:5000/api/structures

GET http://127.0.0.1:5000/api/structures/8c8293a08d9c40429daf03dd5fb701b9


POST http://127.0.0.1:5000/api/structures/c5ac15cd74404c4ea8435981871ac469/runs
Content-Type: application/json

POST http://127.0.0.1:5000/api/runs/asdf/events
Content-Type: application/json
{
    "type": "CompletionChunkEvent", 
    "timestamp": 1712776671.316361, 
    "token": " use"
}
