[tool.poetry]
name = "{{cookiecutter.package_name}}"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
griptape = "*"
griptape-tools = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
