name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Init environment 
        uses: ./.github/actions/init-environment 
      - name: Run tests
        run: pytest
